#' Operant-conditioning glossary
#'
#' A beginner-oriented reference of core operant-conditioning concepts, each with
#' a short verified definition, its primary source, and the handbook(s) in the
#' bundled corpus that cover it. Definitions were checked against the literature
#' before entry; see [operant_bibliography()] for the sources.
#'
#' @return A tibble with columns `term`, `category`, `definition`,
#'   `primary_source`, `handbook`.
#' @export
#' @examples
#' g <- operant_glossary()
#' unique(g$category)
#' g[g$category == "Choice and dynamics", c("term", "definition")]
operant_glossary <- function() {
  tibble::tribble(
    ~term, ~category, ~definition, ~primary_source, ~handbook,
    "Law of effect", "Foundations",
    "Responses followed by a satisfying state of affairs become more strongly connected to the situation and more likely to recur; those followed by discomfort are weakened. The seed of all consequence-based learning.",
    "Thorndike (1898, 1911)", "Bouton 2007; McSweeney & Murphy 2014",
    "Operant conditioning", "Foundations",
    "Learning in which the future probability of a voluntary behaviour is changed by its consequences. Skinner's functional reformulation of Thorndike's law of effect, replacing subjective terms with reinforcement and punishment.",
    "Skinner (1938)", "McSweeney & Murphy 2014; Fisher, Piazza & Roane 2021",
    "Respondent (Pavlovian) behaviour", "Foundations",
    "Reflexive, involuntary behaviour elicited by an antecedent stimulus (e.g. salivation to food). Contrasted with operant behaviour; the domain of classical conditioning.",
    "Pavlov (1927); Skinner (1938)", "McSweeney & Murphy 2014; Bouton 2007",
    "Operant behaviour", "Foundations",
    "Voluntary behaviour that operates on the environment and is controlled by its consequences, as opposed to being elicited by a prior stimulus.",
    "Skinner (1938)", "McSweeney & Murphy 2014; Fisher, Piazza & Roane 2021",
    "Three-term contingency (A-B-C)", "Foundations",
    "The unit of operant analysis: an antecedent (discriminative stimulus) sets the occasion for a behaviour (response) that produces a consequence (reinforcer or punisher). Formalised by Skinner in the early 1950s.",
    "Skinner (1953)", "Fisher, Piazza & Roane 2021; Matson 2023",
    "Reinforcement", "Consequences",
    "A consequence that increases the future frequency of the behaviour it follows. Defined functionally by its effect, not by whether it feels pleasant.",
    "Skinner (1938)", "Fisher, Piazza & Roane 2021; McSweeney & Murphy 2014",
    "Punishment", "Consequences",
    "A consequence that decreases the future frequency of the behaviour it follows. Like reinforcement, defined by its effect on behaviour.",
    "Skinner (1938)", "Fisher, Piazza & Roane 2021; Matson 2023",
    "Positive reinforcement", "Consequences",
    "Adding a stimulus after a behaviour to increase that behaviour (e.g. food after a lever press). 'Positive' means a stimulus is presented, not that the outcome is good.",
    "Skinner (1938)", "Fisher, Piazza & Roane 2021",
    "Negative reinforcement", "Consequences",
    "Removing or postponing an aversive stimulus after a behaviour to increase that behaviour (e.g. a response that turns off a loud noise). Underlies escape and avoidance.",
    "Skinner (1938)", "Fisher, Piazza & Roane 2021; Bouton 2007",
    "Positive punishment", "Consequences",
    "Adding an aversive stimulus after a behaviour to decrease it (e.g. a reprimand following an action).",
    "Skinner (1938)", "Fisher, Piazza & Roane 2021",
    "Negative punishment", "Consequences",
    "Removing a desirable stimulus after a behaviour to decrease it (e.g. loss of a privilege). Includes response cost and timeout.",
    "Skinner (1938)", "Fisher, Piazza & Roane 2021; Matson 2023",
    "Primary (unconditioned) reinforcer", "Consequences",
    "A stimulus that is reinforcing without prior learning because of its biological significance (e.g. food, water).",
    "Skinner (1938)", "Bouton 2007; McSweeney & Murphy 2014",
    "Conditioned (secondary) reinforcer", "Consequences",
    "A previously neutral stimulus that acquires reinforcing power by being paired with an established reinforcer (e.g. a clicker, money).",
    "Skinner (1938)", "Bouton 2007; McSweeney & Murphy 2014",
    "Generalised reinforcer", "Consequences",
    "A conditioned reinforcer paired with many different reinforcers, so it is effective across motivational states (e.g. money, tokens, praise).",
    "Skinner (1953)", "Fisher, Piazza & Roane 2021",
    "Discriminative stimulus (S-D)", "Antecedents and stimulus control",
    "An antecedent stimulus in whose presence a response has been reinforced, so it comes to set the occasion for (signal) that response.",
    "Skinner (1938)", "Fisher, Piazza & Roane 2021; McSweeney & Murphy 2014",
    "Stimulus control", "Antecedents and stimulus control",
    "The degree to which an antecedent stimulus alters the probability of a behaviour, established through differential reinforcement across stimuli.",
    "Skinner (1938)", "Fisher, Piazza & Roane 2021; Bouton 2007",
    "Continuous reinforcement (CRF)", "Schedules",
    "A schedule in which every instance of the target response is reinforced. Produces fast acquisition but rapid extinction once reinforcement stops.",
    "Ferster & Skinner (1957)", "McSweeney & Murphy 2014",
    "Partial (intermittent) reinforcement", "Schedules",
    "Reinforcing only some instances of a response. Slower to acquire but more resistant to extinction than continuous reinforcement.",
    "Ferster & Skinner (1957)", "McSweeney & Murphy 2014; Bouton 2007",
    "Fixed-ratio (FR)", "Schedules",
    "Reinforcement after a fixed number of responses. Produces high response rates with a post-reinforcement pause after each reinforcer.",
    "Ferster & Skinner (1957)", "McSweeney & Murphy 2014",
    "Variable-ratio (VR)", "Schedules",
    "Reinforcement after a variable, unpredictable number of responses. Produces high, steady rates and strong resistance to extinction (the gambling schedule).",
    "Ferster & Skinner (1957)", "McSweeney & Murphy 2014",
    "Fixed-interval (FI)", "Schedules",
    "Reinforcement for the first response after a fixed time has elapsed. Produces a scalloped pattern: a pause then acceleration toward the interval's end.",
    "Ferster & Skinner (1957)", "McSweeney & Murphy 2014",
    "Variable-interval (VI)", "Schedules",
    "Reinforcement for the first response after a variable time has elapsed. Produces a steady, moderate rate; the workhorse schedule for studying choice.",
    "Ferster & Skinner (1957)", "McSweeney & Murphy 2014",
    "Partial-reinforcement extinction effect", "Schedules",
    "Behaviour acquired under intermittent reinforcement extinguishes more slowly than behaviour acquired under continuous reinforcement.",
    "Ferster & Skinner (1957)", "Bouton 2007; McSweeney & Murphy 2014",
    "Concurrent schedules", "Choice and dynamics",
    "Two or more reinforcement schedules available simultaneously on separate operanda, used to study how organisms allocate behaviour between alternatives.",
    "Herrnstein (1961)", "McSweeney & Murphy 2014; Bouton 2007",
    "Matching law", "Choice and dynamics",
    "On concurrent variable-interval schedules the relative rate of responding to an alternative approximately equals the relative rate of reinforcement obtained from it: R1/(R1+R2) = r1/(r1+r2).",
    "Herrnstein (1961, 1970)", "McSweeney & Murphy 2014; Bouton 2007",
    "Undermatching, overmatching, bias", "Choice and dynamics",
    "Systematic deviations from strict matching: undermatching (less extreme than predicted, often from frequent switching), overmatching (more extreme, often from a switching penalty), and constant bias toward one alternative.",
    "Baum (1974)", "McSweeney & Murphy 2014",
    "Changeover delay (COD)", "Choice and dynamics",
    "A brief period after switching alternatives during which no reinforcer is delivered, used to suppress reinforcement of switching itself and reduce undermatching.",
    "Herrnstein (1961)", "McSweeney & Murphy 2014",
    "Melioration", "Choice and dynamics",
    "A dynamic choice rule: allocate behaviour toward whichever alternative currently yields the higher local reinforcement rate. It produces matching on concurrent VI-VI but exclusive preference on concurrent VR-VR, and can be suboptimal.",
    "Herrnstein & Vaughan (1980); Vaughan (1981)", "McSweeney & Murphy 2014; Glimcher 2010",
    "Maximisation vs melioration", "Choice and dynamics",
    "Maximisation allocates behaviour to obtain the highest overall reinforcement rate; melioration tracks local rates. They coincide on many schedules but diverge when choosing an option changes its local return, where melioration can be caught short of the optimum.",
    "Vaughan (1981); Herrnstein & Prelec (1991)", "Glimcher 2010; McSweeney & Murphy 2014",
    "Extinction", "Extinction and change",
    "Withholding the reinforcer that previously maintained a response, leading to a gradual decline in responding (often after a transient extinction burst).",
    "Skinner (1938); Ferster & Skinner (1957)", "Bouton 2007; Fisher, Piazza & Roane 2021",
    "Shaping (successive approximation)", "Extinction and change",
    "Building a new behaviour by reinforcing successively closer approximations to a target response.",
    "Skinner (1938)", "Fisher, Piazza & Roane 2021; McSweeney & Murphy 2014",
    "Superstitious behaviour", "Extinction and change",
    "Behaviour strengthened by accidental (non-contingent) reinforcement that happens to follow it, despite no causal relation, as in Skinner's pigeon demonstration.",
    "Skinner (1948)", "McSweeney & Murphy 2014; Bouton 2007"
  )
}

#' Operant-conditioning bibliography
#'
#' The bundled handbook corpus (held in GCS) plus the primary sources cited in
#' [operant_glossary()]. Handbook entries include their GCS location.
#'
#' @return A tibble with columns `key`, `type`, `citation`, `gcs_uri`.
#' @export
#' @examples
#' operant_bibliography()
operant_bibliography <- function() {
  base <- "gs://sondre_brreg_data/losore_schema_engine/aba_references/source_pdfs"
  tibble::tribble(
    ~key, ~type, ~citation, ~gcs_uri,
    "McSweeney & Murphy 2014", "handbook",
    "McSweeney, F. K., & Murphy, E. S. (Eds.) (2014). The Wiley Blackwell Handbook of Operant and Classical Conditioning. Wiley-Blackwell.",
    paste0(base, "/mcsweeney_murphy_2014_wiley_blackwell_conditioning.pdf"),
    "Bouton 2007", "handbook",
    "Bouton, M. E. (2007). Learning and Behavior: A Contemporary Synthesis. Sinauer Associates.",
    paste0(base, "/bouton_2007_learning_and_behavior.pdf"),
    "Fisher, Piazza & Roane 2021", "handbook",
    "Fisher, W. W., Piazza, C. C., & Roane, H. S. (Eds.) (2021). Handbook of Applied Behavior Analysis (2nd ed.). Guilford Press.",
    paste0(base, "/fisher_piazza_roane_2021_2ed.pdf"),
    "Matson 2023", "handbook",
    "Matson, J. L. (Ed.) (2023). Handbook of Applied Behavior Analysis: Integrating Research into Practice. Springer.",
    paste0(base, "/matson_2023_springer.pdf"),
    "Oxford ABA 2015", "handbook",
    "Miltenberger, R. G., Miller, A., & Zerger, H. (2015). Applied Behavior Analysis. In The Oxford Handbook of Cognitive and Behavioral Therapies. Oxford University Press.",
    paste0(base, "/oxford_handbook_aba_2015.pdf"),
    "Glimcher 2010", "handbook",
    "Glimcher, P. W. (2010). Foundations of Neuroeconomic Analysis. Oxford University Press.",
    paste0(base, "/glimcher_2010_foundations_neuroeconomic_analysis.pdf"),
    "Thorndike 1911", "primary",
    "Thorndike, E. L. (1911). Animal Intelligence: Experimental Studies. Macmillan. (Law of effect; precursor in Thorndike, 1898.)",
    NA_character_,
    "Skinner 1938", "primary",
    "Skinner, B. F. (1938). The Behavior of Organisms: An Experimental Analysis. Appleton-Century-Crofts.",
    NA_character_,
    "Skinner 1948", "primary",
    "Skinner, B. F. (1948). 'Superstition' in the pigeon. Journal of Experimental Psychology, 38, 168-172.",
    NA_character_,
    "Skinner 1953", "primary",
    "Skinner, B. F. (1953). Science and Human Behavior. Macmillan.",
    NA_character_,
    "Ferster & Skinner 1957", "primary",
    "Ferster, C. B., & Skinner, B. F. (1957). Schedules of Reinforcement. Appleton-Century-Crofts.",
    NA_character_,
    "Herrnstein 1961", "primary",
    "Herrnstein, R. J. (1961). Relative and absolute strength of response as a function of frequency of reinforcement. Journal of the Experimental Analysis of Behavior, 4, 267-272.",
    NA_character_,
    "Herrnstein 1970", "primary",
    "Herrnstein, R. J. (1970). On the law of effect. Journal of the Experimental Analysis of Behavior, 13, 243-266.",
    NA_character_,
    "Baum 1974", "primary",
    "Baum, W. M. (1974). On two types of deviation from the matching law: Bias and undermatching. Journal of the Experimental Analysis of Behavior, 22, 231-242.",
    NA_character_,
    "Herrnstein & Vaughan 1980", "primary",
    "Herrnstein, R. J., & Vaughan, W. (1980). Melioration and behavioral allocation. In J. E. R. Staddon (Ed.), Limits to Action. Academic Press.",
    NA_character_,
    "Vaughan 1981", "primary",
    "Vaughan, W. (1981). Melioration, matching, and maximization. Journal of the Experimental Analysis of Behavior, 36, 141-149.",
    NA_character_
  )
}
